### ISSUE TITLE
Bad inference Result!

### ISSUE THREAD

**Issue by AbdulFMS** [ibaiGorordo/TfLite-Ultra-Fast-Lane-Detection-Inference#2]
I used the pretrained mode "model_float16_quant.tflite" from this repo https://github.com/PINTO0309/PINTO_model_zoo/tree/main/140_Ultra-Fast-Lane-Detection
but I got the following result:
![out27](https://user-images.githubusercontent.com/99340798/157660163-192884ea-658f-43e0-8b2b-287377f101be.jpg)

and the orginal image is:
![SC600_Forward_20220206130511_26](https://user-images.githubusercontent.com/99340798/157660869-5c2683c5-b2dc-43c9-8eb4-6a259bed8ef2.jpg)

any hints I can do to enhance the output!?
@ibaiGorordo

**Comment by ibaiGorordo** [comment]
Hi,

Apart from the yellow line, the other does not look that bad. I have seen this model getting much worse results. 

I would say, try to crop the image so that the car part at the bottom is not visible and use the CULANE model as I think you were using.
I have tried it and it looks better:
![output](https://user-images.githubusercontent.com/43162939/157669700-9e53cbfb-e5e1-40f8-860e-c64e3b1617b6.jpg)

**Comment by AbdulFMS** [comment]
it works Thank you! 
@ibaiGorordo
